In [1]:
import pandas as pd
import matplotlib as plt
import numpy as np

Data Ingestion

In [2]:
df = pd.read_excel(r"C:\Users\Kalyani\OneDrive\Data Analytics\projects\pandas project\Flight Delay Analysis\flight_delays.xlsx")

Data Profiling

In [3]:
df = df.drop_duplicates()
df

,FlightID,Airline,FlightNumber,Origin,Destination,ScheduledDeparture,ActualDeparture,ScheduledArrival,ActualArrival,DelayMinutes,DelayReason,Cancelled,Diverted,AircraftType,TailNumber,Distance
0,1,United,4558,ORD,MIA,2024-09-01 08:11:00,2024-09-01 08:30:00,2024-09-01 12:11:00,2024-09-01 12:19:00,8,Weather,True,False,Boeing 737,N71066,1031
1,2,Delta,8021,LAX,MIA,2024-09-01 10:25:00,2024-09-01 10:41:00,2024-09-01 13:25:00,2024-09-01 13:27:00,2,Air Traffic Control,True,True,Airbus A320,N22657,1006
2,3,Southwest,7520,DFW,SFO,2024-09-01 16:53:00,2024-09-01 17:05:00,2024-09-01 17:53:00,2024-09-01 18:07:00,14,Weather,True,True,Boeing 737,N95611,2980
3,4,Delta,2046,ORD,BOS,2024-09-01 14:44:00,2024-09-01 15:04:00,2024-09-01 18:44:00,2024-09-01 18:34:00,-10,NaN,False,False,Boeing 777,N90029,1408
4,5,Delta,6049,LAX,SEA,2024-09-01 01:51:00,2024-09-01 02:08:00,2024-09-01 05:51:00,2024-09-01 06:15:00,24,Air Traffic Control,False,True,Boeing 737,N27417,2298
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,1048571,Delta,8720,ORD,SFO,2024-09-01 07:10:00,2024-09-01 07:32:00,2024-09-01 08:10:00,2024-09-01 08:29:00,19,Air Traffic Control,False,False,Boeing 777,N59866,2265
1048571,1048572,American Airlines,2532,ORD,SEA,2024-09-01 06:41:00,2024-09-01 07:02:00,2024-09-01 09:41:00,2024-09-01 10:07:00,26,Weather,False,True,Airbus A320,N44952,525
1048572,1048573,Southwest,6007,LAX,MIA,2024-09-01 09:01:00,2024-09-01 09:17:00,2024-09-01 11:01:00,2024-09-01 11:25:00,24,Weather,False,True,Airbus A320,N58488,955
1048573,1048574,Delta,2578,LAX,MIA,2024-09-01 03:02:00,2024-09-01 03:21:00,2024-09-01 04:02:00,2024-09-01 04:08:00,6,Maintenance,False,False,Airbus A320,N35425,2673
1048574,1048575,American Airlines,6826,ATL,SEA,2024-09-01 19:13:00,2024-09-01 19:19:00,2024-09-01 23:13:00,2024-09-01 23:05:00,-8,NaN,True,True,Airbus A320,N53303,2501

In [4]:
print(df.columns)

Index(['FlightID', 'Airline', 'FlightNumber', 'Origin', 'Destination',
       'ScheduledDeparture', 'ActualDeparture', 'ScheduledArrival',
       'ActualArrival', 'DelayMinutes', 'DelayReason', 'Cancelled', 'Diverted',
       'AircraftType', 'TailNumber', 'Distance'],
      dtype='object')

In [5]:
df.shape

(1048575, 16)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 16 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   FlightID            1048575 non-null  int64
 1   Airline             1048575 non-null  object
 2   FlightNumber        1048575 non-null  int64
 3   Origin              1048575 non-null  object
 4   Destination         1048575 non-null  object
 5   ScheduledDeparture  1048575 non-null  datetime64[ns]
 6   ActualDeparture     1048575 non-null  datetime64[ns]
 7   ScheduledArrival    1048575 non-null  datetime64[ns]
 8   ActualArrival       1048575 non-null  datetime64[ns]
 9   DelayMinutes        1048575 non-null  int64
 10  DelayReason         767243 non-null   object
 11  Cancelled           1048575 non-null  bool
 12  Diverted            1048575 non-null  bool
 13  AircraftType        1048575 non-null  object
 14  TailNumber          1048575 non-null  object
 15  Distance            1048575 non-null  int64
dtypes: bool(2), datetime64[ns](4), int64(4), object(6)
memory usage: 114.0+ MB

In [7]:
df.head()

,FlightID,Airline,FlightNumber,Origin,Destination,ScheduledDeparture,ActualDeparture,ScheduledArrival,ActualArrival,DelayMinutes,DelayReason,Cancelled,Diverted,AircraftType,TailNumber,Distance
0,1,United,4558,ORD,MIA,2024-09-01 08:11:00,2024-09-01 08:30:00,2024-09-01 12:11:00,2024-09-01 12:19:00,8,Weather,True,False,Boeing 737,N71066,1031
1,2,Delta,8021,LAX,MIA,2024-09-01 10:25:00,2024-09-01 10:41:00,2024-09-01 13:25:00,2024-09-01 13:27:00,2,Air Traffic Control,True,True,Airbus A320,N22657,1006
2,3,Southwest,7520,DFW,SFO,2024-09-01 16:53:00,2024-09-01 17:05:00,2024-09-01 17:53:00,2024-09-01 18:07:00,14,Weather,True,True,Boeing 737,N95611,2980
3,4,Delta,2046,ORD,BOS,2024-09-01 14:44:00,2024-09-01 15:04:00,2024-09-01 18:44:00,2024-09-01 18:34:00,-10,NaN,False,False,Boeing 777,N90029,1408
4,5,Delta,6049,LAX,SEA,2024-09-01 01:51:00,2024-09-01 02:08:00,2024-09-01 05:51:00,2024-09-01 06:15:00,24,Air Traffic Control,False,True,Boeing 737,N27417,2298

In [8]:
df.dtypes

FlightID                       int64
Airline                       object
FlightNumber                   int64
Origin                        object
Destination                   object
ScheduledDeparture    datetime64[ns]
ActualDeparture       datetime64[ns]
ScheduledArrival      datetime64[ns]
ActualArrival         datetime64[ns]
DelayMinutes                   int64
DelayReason                   object
Cancelled                       bool
Diverted                        bool
AircraftType                  object
TailNumber                    object
Distance                       int64
dtype: object

In [9]:
df.isna().sum()

FlightID                   0
Airline                    0
FlightNumber               0
Origin                     0
Destination                0
ScheduledDeparture         0
ActualDeparture            0
ScheduledArrival           0
ActualArrival              0
DelayMinutes               0
DelayReason           281332
Cancelled                  0
Diverted                   0
AircraftType               0
TailNumber                 0
Distance                   0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.head(10)

,FlightID,Airline,FlightNumber,Origin,Destination,ScheduledDeparture,ActualDeparture,ScheduledArrival,ActualArrival,DelayMinutes,DelayReason,Cancelled,Diverted,AircraftType,TailNumber,Distance
0,1,United,4558,ORD,MIA,2024-09-01 08:11:00,2024-09-01 08:30:00,2024-09-01 12:11:00,2024-09-01 12:19:00,8,Weather,True,False,Boeing 737,N71066,1031
1,2,Delta,8021,LAX,MIA,2024-09-01 10:25:00,2024-09-01 10:41:00,2024-09-01 13:25:00,2024-09-01 13:27:00,2,Air Traffic Control,True,True,Airbus A320,N22657,1006
2,3,Southwest,7520,DFW,SFO,2024-09-01 16:53:00,2024-09-01 17:05:00,2024-09-01 17:53:00,2024-09-01 18:07:00,14,Weather,True,True,Boeing 737,N95611,2980
3,4,Delta,2046,ORD,BOS,2024-09-01 14:44:00,2024-09-01 15:04:00,2024-09-01 18:44:00,2024-09-01 18:34:00,-10,NaN,False,False,Boeing 777,N90029,1408
4,5,Delta,6049,LAX,SEA,2024-09-01 01:51:00,2024-09-01 02:08:00,2024-09-01 05:51:00,2024-09-01 06:15:00,24,Air Traffic Control,False,True,Boeing 737,N27417,2298
5,6,Southwest,6311,LAX,JFK,2024-09-01 04:00:00,2024-09-01 04:12:00,2024-09-01 05:00:00,2024-09-01 04:55:00,-5,NaN,False,False,Boeing 777,N92652,1386
6,7,Southwest,4188,ORD,JFK,2024-09-01 05:47:00,2024-09-01 06:02:00,2024-09-01 10:47:00,2024-09-01 10:54:00,7,Weather,False,True,Boeing 777,N25382,1674
7,8,Southwest,3179,DFW,MIA,2024-09-01 02:23:00,2024-09-01 02:49:00,2024-09-01 06:23:00,2024-09-01 06:47:00,24,Weather,False,True,Boeing 777,N65410,2931
8,9,American Airlines,3613,ORD,MIA,2024-09-01 00:02:00,2024-09-01 00:29:00,2024-09-01 02:02:00,2024-09-01 02:04:00,2,Weather,False,False,Airbus A320,N45570,2337
9,10,Southwest,2186,LAX,BOS,2024-09-01 10:14:00,2024-09-01 10:39:00,2024-09-01 14:14:00,2024-09-01 14:39:00,25,Maintenance,True,False,Boeing 777,N15724,605

Data Cleaning

In [12]:
df.columns = (
    df.columns
    .str.lower()
    .str.strip()
    .str.replace(" ","_")
)
df.columns

Index(['flightid', 'airline', 'flightnumber', 'origin', 'destination',
       'scheduleddeparture', 'actualdeparture', 'scheduledarrival',
       'actualarrival', 'delayminutes', 'delayreason', 'cancelled', 'diverted',
       'aircrafttype', 'tailnumber', 'distance'],
      dtype='object')

In [13]:
datetime_cols = [
    'scheduleddeparture', 
    'actualdeparture', 
    'scheduledarrival',
    'actualarrival'
]

for cols in datetime_cols:
    df[cols] = pd.to_datetime(df[cols])

In [14]:
df["cancelled"] = df["cancelled"].astype(bool)
df["diverted"] = df["diverted"].astype(bool)

In [15]:
df["Early_flag"] = df["delayminutes"] < 0   #boolean vaule will be stored in this new col to indicate early flights
df.loc[df["delayminutes"] < 0, "delayminutes"] = 0   #negative delay are set to 0
df["delayreason"] = df["delayreason"].fillna("No Delay")   #null changed to no delay

In [16]:
df["origin"] = df["origin"].str.upper().str.strip()
df["destination"] = df["destination"].str.upper().str.strip()

In [17]:
df = df[df["distance"] > 0] #distance should not be zero or negative

df = df[df["flightnumber"].notna()]   #select rows where flight no is not null

SQL Connection

In [21]:
from urllib.parse import quote_plus
from sqlalchemy import create_engine

password = quote_plus("Sharmila@07")

engine = create_engine(
    f"mysql+mysqlconnector://root:{password}@localhost:3306/flight_db",
    pool_pre_ping=True,
    pool_recycle=3600
)

# chunked upload
df.to_sql(
    "flights_cleaned",
    con=engine,
    if_exists="replace",
    index=False,
    chunksize=10000,     # 10k rows per batch
    method="multi"       # bulk insert
)

1048575